### ISSUE TITLE
There is an error in the conversion Testclassname.

### ISSUE THREAD

**Issue by leaders99** [inorton/junit2html#16]
There is an error in the conversion Testclassname in parser.py.

If you are adding a new testcase testclassname already registered, your code can not put testclassname correctly. For example,  the testclassname in xml below is displayed incorrectly.

xml 
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="test" errors="0" failures="0" tests="520" hostname="tbd" time="31.2887" timestamp="2017-06-28T06:10:25Z">
    <testcase classname="global" name="test1" time="3.001676"/>
    <testcase classname="class1" name="test2" time="0.210063"/>
    <testcase classname="class2" name="test3" time="0.605618"/>
    <testcase classname="global" name="test4" time="7.002117"/>
    <testcase classname="class3" name="test5" time="12.026334"/>
    <testcase classname="global" name="test6" time="7.002825"/>
    <system-out/>
    <system-err/>
  </testsuite>
</testsuites>
```

Can you add one line below to parser.py?

diff --git a/junit2htmlreport/parser.py b/junit2htmlreport/parser.py
index 5d85824..f0637c1 100644
--- a/junit2htmlreport/parser.py
+++ b/junit2htmlreport/parser.py
@@ -443,6 +443,9 @@ class Junit(object):
 
                         cursuite[testclass.name] = testclass
 
+                    #testclass name buf fix
+                    testclass = cursuite[testcase.attrib["classname"]]
+
                     newcase = Case()
                     newcase.name = testcase.attrib["name"]
                     newcase.testclass = testclass

**Comment by inorton** [comment]
I'm happy to accept a pull request
