### ISSUE TITLE
Add screenshots

### ISSUE THREAD

**Issue by msabramo** [inorton/junit2html#19]
It would be nice to see what the output looks like.

**Comment by inorton** [comment]
I'll see what I can do :)

**Comment by avk2** [comment]
yes pls, it would be appreciated

**Comment by oppianmatt** [comment]
even better a demo page of a result

**Comment by inorton** [comment]
Latest example reports availible at https://gitlab.com/inorton/junit2html/-/jobs/artifacts/master/browse?job=python36
