### ISSUE TITLE
Fixing error for parsing time when string representing time has comma in between. Eg. (27,700.56)

### ISSUE THREAD

**Issue by Rssingh3** [inorton/junit2html#21]
This can be solved by doing small edits at 
1. Line no.428 can be replaced by 
 _`cursuite.duration = float(suite.attrib.get("time", '0').replace(',',''))`_
2. Line no.450 can be replaced by 
 _`newcase.duration = float(testcase.attrib.get("time", '0').replace(',',''))`_

**Comment by inorton** [comment]
Many thanks, Can you make a pull request?
