### ISSUE TITLE
KeyError: 'classname' on MacOS

### ISSUE THREAD

**Issue by BalintSzigeti** [inorton/junit2html#23]
hello

If I run junit2html <file>.xml <file>.html then get 

> Traceback (most recent call last):
>   File "/usr/local/bin/junit2html", line 4, in <module>
>     runner.start()
>   File "/Library/Python/2.7/site-packages/junit2htmlreport/runner.py", line 45, in start
>     run(sys.argv[1:])
>   File "/Library/Python/2.7/site-packages/junit2htmlreport/runner.py", line 29, in run
>     report = parser.Junit(args[0])
>   File "/Library/Python/2.7/site-packages/junit2htmlreport/parser.py", line 387, in __init__
>     self.process()
>   File "/Library/Python/2.7/site-packages/junit2htmlreport/parser.py", line 438, in process
>     if testcase.attrib["classname"] not in cursuite:
> KeyError: 'classname'

I use Python 2.7.10

**Comment by inorton** [comment]
Hi, Can you send me an example xml file that triggers this?

**Comment by BalintSzigeti** [comment]
hm,... I can't reproduce the issue anymore.
