### ISSUE TITLE
Is it possible to use several .xml files as input?

### ISSUE THREAD

**Issue by fkromer** [inorton/junit2html#25]
Is it possible to use several .xml files as input, e.g. `junit2html pytest-results.xml another-frameworks-result.xml single-output-file.html`?

**Comment by inorton** [comment]
No, but that is quite easy with a tool like xargs:
`ls *-results.xml` |xargs junit2html

**Comment by inorton** [comment]
Oh I see what you mean! Hmm yes, I'll think about that

**Comment by inorton** [comment]
Moved this to https://gitlab.com/inorton/junit2html/issues/1
