### ISSUE TITLE
Getting "UnboundLocalError: local variable 'suites' referenced before assignment"

### ISSUE THREAD

**Issue by abhiras29** [inorton/junit2html#29]
Traceback (most recent call last):
  File "junit2html", line 4, in <module>
    runner.start()
  File "C:\Python27\lib\site-packages\junit2htmlreport\runner.py", line 45, in start
    run(sys.argv[1:])
  File "C:\Python27\lib\site-packages\junit2htmlreport\runner.py", line 29, in run
    report = parser.Junit(args[0])
  File "C:\Python27\lib\site-packages\junit2htmlreport\parser.py", line 419, in __init__
    self.process()
  File "C:\Python27\lib\site-packages\junit2htmlreport\parser.py", line 454, in process
    for suite in suites:
UnboundLocalError: local variable 'suites' referenced before assignment

**Comment by inorton** [comment]
Can you attach a XML file that provokes this?

**Comment by abhiras29** [comment]
Please find attached the xml, which caused the same(change the extension to xml)
But in my opinion this is something related to Code issue in Parser.py at line 454
we have one for loop (for suite in suites: ), which is trying to use suites which is not initialized anywhere in "process"
[CaseManagementConfidenceTestSuite_20171113-124043 - Copy.txt](https://github.com/inorton/junit2html/files/1473549/CaseManagementConfidenceTestSuite_20171113-124043.-.Copy.txt)
 function

**Comment by inorton** [comment]
I think I understand,  your file contains a top level <testsuite> that also contains <testsuite> tags.  I'd not encountered nested test suites before.

**Comment by abhiras29** [comment]
Yes, I am getting an empty HTML file after fixing this bug
Solution : In process function, we can initialize suites as "suites = []"
After this change I am getting HTML file generated but it is all empty, attaching the same to this post
[Results - Copy.txt](https://github.com/inorton/junit2html/files/1481280/Results.-.Copy.txt)
(**Change the extention to html to test the file)**

**Comment by abhiras29** [comment]
I tried to change Tag structure of my xml file and able to get the results file
I changed <testrun> tag and parent <testsuite> to <testsuites>

**Comment by inorton** [comment]
I see, I've never encountered nested test suites either.  I'll look at if the spec expects this to be valid.

**Comment by inorton** [comment]
Can you send me your latest input file?  I will probably alter the code to cope better and be more informative, but I don't want to necessarily do things that other junit tools can't

**Comment by abhiras29** [comment]
Yes you are right, usually <testrun> tag and nested wont come in Junit xml
But when you try to run any test suite class from Eclipse, then you will get this type xml(attached)
Which is also a very common scenario for Junits
[CaseManagementConfidenceTestSuite_20171113-124043 - Copy.txt](https://github.com/inorton/junit2html/files/1487001/CaseManagementConfidenceTestSuite_20171113-124043.-.Copy.txt)

**Comment by inorton** [comment]
Thanks, I've never seen `<testrun>`

**Comment by inorton** [comment]
There you go, I've put version 010 on pypi now
