### ISSUE TITLE
How to use in Windows?

### ISSUE THREAD

**Issue by lovesoo** [inorton/junit2html#32]
1.  download the zip and use "python setup.py install"  command to install junit2html successfully
2.  use the command "junit2html "
3.  I got the error "junit2html is not recognized as an internal or external command, operable program or batch file." Even though path is added

**Comment by inorton** [comment]
On windows the script gets installed in the `scripts` directory. You can find out where this is by doing:

`
python.exe -c "import sys;print sys.exec_prefix"
`

Which on my system prints:
`
c:\python27
`

So you can do:

`
python "c:\python27\scripts\junit2html" report.xml
`

**Comment by lovesoo** [comment]
Thanks, It Works Now!

**Comment by inorton** [comment]
I just pushed an upload to pypi too,  So if you install the latest update you should instead be able to do:
`python -m junit2htmlreport report.xml`

**Comment by lovesoo** [comment]
Thanks, actually I used in this way before and It worked.

`from junit2htmlreport import runner
runner.run(['test.xml','test.html'])
`
