### ISSUE TITLE
Processing several XML files at a time (`junit2html test/results/*.xml`)

### ISSUE THREAD

**Issue by fgalan** [inorton/junit2html#36]
I have several XML result in the behave results directory:

```
$ ls tests/results/*.xml
tests/results/TESTS-features.TS02_iotaflows.016_iotaul2autoprovision.xml  
tests/results/TESTS-features.TS02_iotaflows.017_iotajson2autoprovision.xml
```

However, `junit2html test/results/*.xml` doesn't work. I have to run junit on each individual .xml file to get the corresponding .html generated.

Moreover, it would be great that when junit processes several XML (using the suggested way `junit2html test/results/*.xml`) it generates some index.html page to cover all them. That way, the HTML resport would have a more integrated view.

Reference junit2html version:

```
$ pip freeze | grep junit2html
junit2html==18
```

**Comment by inorton** [comment]
Hi there, junit2html has now moved to https://gitlab.com/inorton/junit2html.

If you install the latest version via pip the latest version support combining several reports into one as well as a kind of multi-dimensional report.

`
junit2html --merge=merged.xml report1.xml report2.xml reportN.xml
`
