### ISSUE TITLE
Displaying failure/error at start

### ISSUE THREAD

**Issue by rahulLiving** [inorton/junit2html#37]
Very helpful tool. But wouldn't it be nice to display the failure/error results at top of html page only. Here one has to lookout entire html page to find failures ?

**Comment by rahulLiving** [comment]
Okay so i came across this repo (https://gitlab.com/inorton/junit2html/tree/matrix-report) which is supposed to generate matrix based result which does what i am looking for. But i am still getting that one page html output ? Any idea why ?

**Comment by inorton** [comment]
Hiya.  I've merged the "matrix-report" branch already.  You can see the live examples here:

https://inorton.gitlab.io/-/junit2html/-/jobs/50953666/artifacts/junit2htmlreport/tests/matrix-example.html

You get one "matrix" index page and also generated pages for the individual reports that make up the matrix columns.

Are you suggesting that each report page should have a summary table near the top of the page (before the index?) that shows the pass/fail tally?

**Comment by rahulLiving** [comment]
The matrix output does serve that purpose. 

But even on using the above mentioned repo((https://gitlab.com/inorton/junit2html/tree/matrix-report), i get that one page html output which says its a matrix-report but i see one page html report. 
This is the format the output is going to **junit2html-matrix-report-808bf643ab3710dd4b2f73b073b8ef5692ab4e00/out.html**.

So just wondering if there is anything special to get a matrix-report html output

**Comment by inorton** [comment]
I'm not sure what you mean, could you maybe mock up an example?

**Comment by rahulLiving** [comment]
[UNIT-TEST.xml - Junit Test Report.pdf](https://github.com/inorton/junit2html/files/1713385/UNIT-TEST.xml.-.Junit.Test.Report.pdf)
Yeah sure. So i have cloned (https://gitlab.com/inorton/junit2html/tree/matrix-report) this repo

And when i ran **junit2html UNIT-TEST.xml out.html**

I got an html which looks like this(converted to pdf)

**Comment by inorton** [comment]
The tool has several command line options that control the output mode.

To get the tool to generate you a page with a matrix table you must do:

```
python -m junit2htmlreport --report-matrix junit2htmlreport/tests/matrix.html junit2htmlreport/tests/junit-axis-linux.xml
```

**Comment by rahulLiving** [comment]
Oh yeah, its this one. It would be good to mention the same in README too.
Thanks
