### ISSUE TITLE
Support `[[ATTACHMENT|path/to/file]]`? 

### ISSUE THREAD

**Issue by pavel-kolesnikov** [inorton/junit2html#47]
Please support the `Attachment` pattern:
```xml
<system-out>
....
[[ATTACHMENT|/absolute/path/to/some/file]]
....
</system-out>
```
(see [Jenkins](https://plugins.jenkins.io/junit-attachments/) or [MSDN Forums](https://social.msdn.microsoft.com/Forums/vstudio/en-US/01bfd9ad-e1eb-4039-a181-c1a4ba87ec39/publish-attachments-using-junit-format-in-automated-build?forum=TFService))

**Comment by inorton** [comment]
Hi Pavel, this is curious, I would have thought this would continue to work with merged report files as it is just normal system-out content.  What doesn't work?

**Comment by pavel-kolesnikov** [comment]
Seems a misunderstanding. :)

I really hoped that writing the `[[ATTACHMENT|/absolute/path/to/some/file]]` would be enough to have at least link to attached file in the report HTML body. Ideally, output should depend on file type. For images `<img src="/absolute/path/to/some/file" />` to be injected.

**Comment by inorton** [comment]
Hi Pavel, I'm not sure how I can make this work in a robust way, any links generated would have to be in cooperation of the webserver hosting the junit html.

**Comment by pavel-kolesnikov** [comment]
> any links generated would have to be in cooperation of the webserver hosting the junit html
The simplest way is to make `href`\`src` of a link in report be exactly equal to `ATTACHMENT` value. And that attachment value could be relative path to report file. Relative path works well for both local path and Web scenario. It is the `junit2html` user's duty to make the attachment available for the web server on that path.

So, that algorithm is such:
- `[test author]` writes a file to the path relative to the XML report. E.g. `logs/test-11111.log` and  `shots/shot-01.png`.
- `[test author]` writes `[ATTACHMENT|`logs/test-11111.log`] to the test's stdout. Now we have it in our report
- `[junit2html user]` calls `junit2html` to make HTML report from XML.
- `[junit2html user]` copies converted HTML report and all the files around it (with `logs/test-11111.log` included) to some location served by HTTP server like `/www/reports/my-great-product/unique-test-id`.
- `[HTTP server]` serves HTML report from (lets say) `https://reports.local` 
- - The url of report could be `https://reports.local/my-great-product/unique-test-id/report.html` (or even index.html, but that is easily achieved outside of `junit2html`)
- - There are `<img src="shots/shot-01.png">` and `<a href="logs/test-11111.log"/>logs/test-11111.log</a>` in the report. They still works cause they're relative to the report's file.

Other scenarios could be achieved by the `[test author]` as (s)he knows how the report server works and change `[ATTACHMENT|....]` text accordingly.

**Comment by BenjaminLaschkar** [comment]
I hacked this with some bash by replacing all TEST-junit-jupiter.xml.html with report_name.xml.html

```
# Save html report to /reports folder and keeping /xml.html 
junit2html ./reports/TEST-junit-jupiter.xml --report-matrix ./reports/REPORT.html
date=`date +"%Y-%m-%d_%H-%M"`
report_name="report_${date}"
sed -i "s/TEST-junit-jupiter/xml\/${report_name}/g" ./reports/REPORT.html
mv ./reports/TEST-junit-jupiter.xml.html ./reports/xml/${report_name}.xml.html
mv ./reports/REPORT.html ./reports/${report_name}.html
rm ./reports/TEST-junit-jupiter.xml
echo "Test finished! and report created in this folder : $report_name"
echo "file://$PATH_HOST/reports/$report_name.html"
````

I have this tree :
```
---reports
     ---report_2021-11-23_20-50.html
     ---report_2021-11-23_20-55.html
     ---xml
          ----report_2021-11-23_20-50.xml.html
          ----report_2021-11-23_20-55.xml.html
```

If there is a better solution please share 💯

**Comment by inorton** [comment]
Hi @BenjaminLaschkar   This seems to be a feature of a jenkins plugin rather than part of the junit spec.

I don't think I will include this into junit2html.

**Comment by BenjaminLaschkar** [comment]
Hello, I think I readed too fast and misunderstood the meaning of "attachement here". I will open a new issue
