### ISSUE TITLE
test.failed branch statement ignored in report.html

### ISSUE THREAD

**Issue by N3bukadne7ar** [inorton/junit2html#48]
In the main template file  report.html two different syntax are used to asses if a test case has failures 

line 29: 
{% if test.failed() %}
lines83, 91: 
{% if test.failed %}

It seems second variant will return true even if no failures, or the branch statement be disregarded, because for me this caused elements associated with failures to be printed into the output file, despite no failures in the test. Adding the brackets fixed it.

**Comment by inorton** [comment]
Moved to https://gitlab.com/inorton/junit2html/-/issues/28
