### ISSUE TITLE
Merge multiple files and generate html report in a single command

### ISSUE THREAD

**Issue by kishaningithub** [inorton/junit2html#50]
Currently we have multiple junit xml files generated it would be great if this can be merged and output in a single command

```bash
python3  -m junit2htmlreport ./reports/*.xml ./reports/full-report.html
```

The above does not work and prints the usage notes, what works is

```bash
python3  -m junit2htmlreport --merge ./reports/full-report.xml ./reports/*.xml
python3  -m junit2htmlreport ./reports/full-report.xml ./reports/full-report.html
```

Can this be merged as a single command?

**Comment by inorton** [comment]
moved to https://gitlab.com/inorton/junit2html/-/issues/27

**Comment by Mahesh-Kumbhar1** [comment]
This above command generating blank full-report.xml file. Any solution for this?
