### ISSUE TITLE
Error while generating html SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by sonudavidson** [inorton/junit2html#52]
I get an error when I tried to generate html from the junit xml file I have.

D:\junit2html-master>C:\Python27\python.exe junit2html D:\junit2html-master\tests\junit-complex_suites.xml D:\junit-complex_suites.html
Traceback (most recent call last):
  File "junit2html", line 3, in <module>
    from junit2htmlreport import runner
  File "D:\junit2html-master\junit2htmlreport\runner.py", line 7, in <module>
    from junit2htmlreport import parser, matrix, merge
  File "D:\junit2html-master\junit2htmlreport\parser.py", line 10, in <module>
    from .render import HTMLReport
  File "D:\junit2html-master\junit2htmlreport\render.py", line 19
    def __str__(self) -> str:
                      ^
SyntaxError: invalid syntax

xml file used is the xml from tests directory. tests\junit-complex_suites.xml 
Am I doing something wrong?

Thanks in advance.

--
Sonu

**Comment by dmiro** [comment]
It looks like your version of the code is incorrect or has been modified.
should be `__str__` instead of `str`

**render.py, line 19:**
```
def __str__(self) -> str:
        env = Environment(
            loader=PackageLoader("junit2htmlreport", "templates"),
            autoescape=select_autoescape(["html"])
        )
```

**Comment by inorton** [comment]
@dmiro  I expect @sonudavidson had his pasted code turned into markdown which is why it is showing **str**  and not __str__

**Comment by inorton** [comment]
Hi @sonudavidson,  junit2html no longer supports python2 - see https://www.python.org/doc/sunset-python-2/

**Comment by dmiro** [comment]
I need to graduate my glasses again. 😄
