### ISSUE TITLE
Skipped test are not marked with [S] 

### ISSUE THREAD

**Issue by ndinev** [inorton/junit2html#54]
Steps:
1. make sure you have one skipped tests case in your xml report
2. run conversion to html
3. explore the html 

You will see that test is not marked with [S] in the summary  on top as expected
However if you scroll down to this test details you can see it is marked correctly as skipped (with yellow)

you can reproduce with examples within this repo:
junit2html tests\junit-axis-windows.xml r.html

**Comment by dmiro** [comment]
Junit2html is maintained on gitlab at https://gitlab.com/inorton/junit2html
please, report issue on gitlab

**Comment by inorton** [comment]
@ndinev thanks for the report, I've logged it on gitlab https://gitlab.com/inorton/junit2html/-/issues/31
