### ISSUE TITLE
Add Test Run Time and Date to reports and merged report sections

### ISSUE THREAD

**Issue by rhempel** [inorton/junit2html#56]
The first line of the JUnit report may have a time field that indicates when the test was executed - see the example below from the -ojunit option of CppUTest:

<testsuite errors="0" failures="1" hostname="localhost" name="Realloc" tests="10" time="0.000" timestamp="2023-09-10T15:15:57">

The number of tests and time are already visible, is it possible to add the timestamp (and potentially hostname) as well?

The reason is for traceability - the generated report is visible in our project dashboard - so having the timestamp clearly visible makes it easy to see when the last run was :-)

**Comment by dmiro** [comment]
Junit2html is maintained on gitlab at https://gitlab.com/inorton/junit2html
please, report issue on gitlab

**Comment by inorton** [comment]
Many thanks for the report @rhempel - Moved to gitlab https://gitlab.com/inorton/junit2html/-/issues/30

**Comment by inorton** [comment]
> The first line of the JUnit report may have a time field that indicates when the test was executed - see the example below from the -ojunit option of CppUTest:
> 
> The number of tests and time are already visible, is it possible to add the timestamp (and potentially hostname) as well?
> 
> The reason is for traceability - the generated report is visible in our project dashboard - so having the timestamp clearly visible makes it easy to see when the last run was :-)

Do you happen to have any sample reports you can link to?
