### ISSUE TITLE
support  for more Testsuites 

### ISSUE THREAD

**Issue by jlanik** [inorton/junit2html#6]
The program crashes if the root element is not <testsuite>.
However it is common for <testsuite> nodes to be wrapped in one root <testsuites> node. 

I need this to work, I will provide a pull request if I manage to fix it myself

**Comment by inorton** [comment]
Do you have any examples you could paste?

**Comment by inorton** [comment]
I've had a  go at fixing this. We should now be able to handle and render a report that contains multiple suites. I've added some tests for this too

**Comment by inorton** [comment]
I'm marking this as fixed :)
