### ISSUE TITLE
KeyError: 'time'

### ISSUE THREAD

**Issue by Segmose** [inorton/junit2html#9]
Im getting the following error
junit2html someproject.xml

Traceback (most recent call last):
  File "/usr/local/bin/junit2html", line 4, in <module>
    runner.start()
  File "/usr/local/lib/python2.7/dist-packages/junit2htmlreport/runner.py", line 40, in start
    run(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/junit2htmlreport/runner.py", line 29, in run
    report = parser.Junit(args[0])
  File "/usr/local/lib/python2.7/dist-packages/junit2htmlreport/parser.py", line 387, in __init__
    self.process()
  File "/usr/local/lib/python2.7/dist-packages/junit2htmlreport/parser.py", line 449, in process
    newcase.duration = float(testcase.attrib["time"])
KeyError: 'time'

The problem seem to be solved by changing the line to 

`newcase.duration = float(testcase.attrib.get("time", '0'))`

**Comment by inorton** [comment]
If you'd like to make a fork and submit a pull request I'd be happy to accept it (then you get credit in the commit messages too)

**Comment by inorton** [comment]
Could you perhaps give me a xml file too? It would be nice to know what tools produce these files (so far working with py.test, junit and some cunit xslt)

**Comment by Segmose** [comment]
Using [CUTE 2.0](http://cute-test.com/) in a C++ project.
The output is supposed to be junit compatible

Found your [post](http://stackoverflow.com/a/37954150) and decided to try it out as I wanted to visualize the results.

I'll try to find out how to fork and make a pull request.

**Comment by Segmose** [comment]
And the xml file.
[zipped.zip](https://github.com/inorton/junit2html/files/611630/zipped.zip)

**Comment by inorton** [comment]
Just merged the fix for this

**Comment by inorton** [comment]
I think I might add a subset of your XML into the unit tests

**Comment by Segmose** [comment]
Nice, just please anonymize it a bit.
